services:
  sdr:
    build:
      context: .
      dockerfile: Dockerfile.rtl433
    devices:
      - "/dev/bus/usb"
    depends_on:
      - sdr_relay
  sdr_relay:
    build:
      context: .
      dockerfile: Dockerfile.graphite_relay
    ports:
      - "1433:1433"
    environment:
      - GRAPHITE_HOST=${GRAPHITE_HOST}
      - GRAPHITE_PORT=${GRAPHITE_PORT}
      - GRAPHITE_PREFIX=${GRAPHITE_PREFIX}
 # nodered:
 #   image: nodered/node-red-docker:latest
 #   ports:
 #     - "1880:1880"
 #   volumes:
 #     - ./nodered:/data
 #   depends_on:
 #     - sdr
 # mosquitto:
 #   image: eclipse-mosquitto:latest
 #   ports:
 #     - "1883:1883"
 #     - "9001:9001"
 #   volumes:
 #     - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
 #     - ./mosquitto/data:/mosquitto/data
 #     - ./mosquitto/log:/mosquitto/log
 #   depends_on:
 #     - nodered