services:
  sdr:
    build:
      context: .
      dockerfile: Dockerfile.rtl433
    devices:
      - "/dev/bus/usb"
    depends_on:
      - sdr_relay
  sdr_relay:
    build:
      context: .
      dockerfile: Dockerfile.graphite_relay
    ports:
      - "1433:1433"
    environment:
      - GRAPHITE_HOST=${GRAPHITE_HOST}
      - GRAPHITE_PORT=${GRAPHITE_PORT}
      - GRAPHITE_PREFIX=${GRAPHITE_PREFIX}